
        <!--<link rel="stylesheet" href="http://yui.yahooapis.com/2.9.0/build/reset/reset-min.css">-->
        <link rel="stylesheet" href="<?php  echo url_for('stylesheets/css/stylesheet.css');?>">
        <link rel="stylesheet" href="<?php echo url_for('stylesheets/formCss.css');?>">
               <style>
            /*
TEXT COLOR OF A TEXT WHICH IS GENERATED BY EDITORTEXT
*/

.wysiwyg-color-black {
  color: black;
}

.wysiwyg-color-silver {
  color: silver;
}

.wysiwyg-color-gray {
  color: gray;
}

.wysiwyg-color-white {
  color: white;
}

.wysiwyg-color-maroon {
  color: maroon;
}

.wysiwyg-color-red {
  color: red;
}

.wysiwyg-color-purple {
  color: purple;
}

.wysiwyg-color-fuchsia {
  color: fuchsia;
}

.wysiwyg-color-green {
  color: green;
}

.wysiwyg-color-lime {
  color: lime;
}

.wysiwyg-color-olive {
  color: olive;
}

.wysiwyg-color-yellow {
  color: yellow;
}

.wysiwyg-color-navy {
  color: navy;
}

.wysiwyg-color-blue {
  color: blue;
}

.wysiwyg-color-teal {
  color: teal;
}

.wysiwyg-color-aqua {
  color: aqua;
}
/*TEXT COLOR OF A TEXT WHICH IS GENERATED BY EDITORTEXT*/
        </style>
        <script src="<?php echo url_for('stylesheets/parser_rules/advanced.js')?>" ></script>
        <script src="<?php echo url_for('stylesheets/dist/wysihtml5-0.3.0.js');?>" ></script>
        <!--<script src="<?php echo url_for('stylesheets/formJs.js');?>" ></script>-->
        
        
  